### PR TITLE
Update with the Polymer 1.1 style recommendations

### PR DESCRIPTION
**Pull request by abdonrd**

### CODE REVIEW

**Comment by samccone** [comment]
lgtm thanks @abdonrd :penguin:

**Comment by addyosmani** [comment]
LGTM2.

**Comment by notwaldorf** [comment]
Thanks! I'll merge it and steal the contribution squares from @addyosmani on this 😛💖

**Comment by notwaldorf** [comment]
FYI the tests are broken because of a bad import in the test file. I'll fix it in a separate PR

**Comment by abdonrd** [comment]
Your welcome! :)

**Comment by samccone** [comment]
great work @abdonrd :clap:

**Pull request merged**
